apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/saikiran243/k8sobserve.git' # Your Repo!
    targetRevision: HEAD
    path: apps/target-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true