apiVersion: apps/v1
kind: Deployment
metadata:
  name: target-app
  labels:
    app: target-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: target-app
  template:
    metadata:
      labels:
        app: target-app
    spec:
      containers:
        - name: target-app
          image: nginx:latest
          resources:
            limits:
              memory: 256Mi # Hardcoded for simplicity, but tied to values in a real Helm chart
            requests:
              memory: 128Mi